TISSUE:
  geometry: cylindrical
  rcap: 5
  variant: "piecewise_approx"
  kon: .0003600000
  kd: 5.000
  mt: 10.0
  D: .0100000000
  s_init: 9.99
  c0:
    - "constant"
    - 0
  tissue_length: 50
  spatial_res: 1.0

SOLVER:
  tmax: 259200
  dt: 0.01
  dt_track: 60.0
